env:  
  node: true  
extends:  
  - plugin:@typescript-eslint/recommended  
  - prettier 
ignorePatterns: ['**/build/**/*.js']
overrides: 
  - files: ['*.ts', '*.tsx']
parser: '@typescript-eslint/parser'  
parserOptions:  
  ecmaVersion: 9  
  project: ./tsconfig.json  
rules: 
  "@typescript-eslint/explicit-module-boundary-types": off
  '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }]
plugins:  
 - '@typescript-eslint'